type User {
  _id: ID
  username: String!
  email: String!
  firstName: String
  lastName: String
}

input UserInput {
  username: String!
  email: String!
  firstName: String
  lastName: String
}